% #!/bin/sh
qsub -N long_cell_112616_cell09 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_long_time_scale_plasticity_rule_variable_run_vel_112616 9'
qsub -N long_cell_112616_cell10 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_long_time_scale_plasticity_rule_variable_run_vel_112616 10'
qsub -N long_cell_112616_cell11 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_long_time_scale_plasticity_rule_variable_run_vel_112616 11'
qsub -N short_cell_112616_cell01 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 1'
qsub -N short_cell_112616_cell02 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 2'
qsub -N short_cell_112616_cell03 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 3'
qsub -N short_cell_112616_cell04 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 4'
qsub -N short_cell_112616_cell05 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 5'
qsub -N short_cell_112616_cell06 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 6'
qsub -N short_cell_112616_cell07 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 7'
qsub -N short_cell_112616_cell08 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 8'
qsub -N short_cell_112616_cell09 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 9'
qsub -N short_cell_112616_cell10 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 10'
qsub -N short_cell_112616_cell11 -m e -M milsteina@janelia.hhmi.org -j y -o /dev/null -b y -cwd -V 'python optimize_short_time_scale_plasticity_rule_variable_run_vel_112616 11'