simulation:
  morph_filename: EB2-late-bifurcation.swc
  mech_filename: 20260426_default_biophysics_with_Poirazi_Ca_Ch_and_2018_Kca.yaml
  equilibrate: 250.0
  baseline: 10
  sim_duration: 1500.0
  dt: 0.025
  v_init: -70.0

  input_resistance_test_start: 270.0
  input_resistance_test_duration: 100.0
  input_resistance_test_amp: -50.0

  rheobase_test_start: 390.0
  rheobase_test_duration: 500.0
  rheobase_test_amps:
  - 0.0
  - 25.0
  - 50.0
  - 75.0
  - 100.0
  - 125.0
  - 150.0
  - 175.0
  - 200.0
  - 225.0

  #f-I curve test - following input resistance test after 20ms baseline
  fi_test_start: 390.0
  fi_test_duration: 500.0
  fi_test_amps:
  - 0.0
  - 50.0
  - 100.0
  - 150.0
  - 200.0
  - 250.0
  - 300.0
  - 350.0
  #following input resistance test after 20ms baseline - 300ms ISI
  ECIII_epsp_times:
  - 390.0
  - 690.0
  - 990.0
  CA3_epsp_times:
  - 390.0
  - 690.0
  - 990.0
  burst_starts_ms:
  - 390.0
  - 540.0
  - 690.0
  - 840.0
  - 990.0
  burst_duration_ms: 150.0
  trough_window_ms: 50.0
  theta_stim_win_start_ms: 390.0
  theta_stim_win_end_ms: 1290.0
  pulses_per_burst: 5
  intra_burst_interval_ms: 10.0
  excitatory_stochastic: True

