bounds:
    # --- L-type Calcium (cal) ---
    cal_gcalbar_soma:   [0.001, 0.02]
    cal_gcalbar_trunk:  [0.001, 0.02]
    # your modify_mechanisms_function needs to apply any apical values to the basal branches with the same distance-dependence
    cal_gcalbar_apical: [0.001, 0.02]
    cal_gcalbar_tuft:   [0.001, 0.02]

    # --- High-Threshold L-type (calH) ---
    # (Trunk/Apical values represent the distal maximum)
    calH_gcalbar_soma:   [0.00001, 0.0001]
    calH_gcalbar_trunk:  [0.0005, 0.005]
    calH_gcalbar_apical: [0.0005, 0.005]
    calH_gcalbar_tuft:   [0.0005, 0.005]

    # --- R-type Calcium (car) ---
    car_gcabar_soma:    [0.001, 0.01]
    car_gcabar_trunk:   [0.00001, 0.0001]
    car_gcabar_apical:  [0.00001, 0.0001]
    car_gcabar_tuft:    [0.00001, 0.0001]

    # --- T-type Calcium (cat) ---
    # (Trunk value represents the distal maximum at 350um)
    cat_gcatbar_soma:   [0.00001, 0.0002]
    cat_gcatbar_trunk:  [0.0001, 0.001]
    cat_gcatbar_apical: [0.0001, 0.001]
    cat_gcatbar_tuft:   [0.0001, 0.001]

    # --- Synaptic Weights & Counts ---
    gabab_gmax:        [0.00001, 0.0002]
    num_exc_syns_CA3:   [50, 250]
    num_exc_syns_ECIII: [80, 400]
    num_inh_syns_CA3:   [60, 300]
    num_inh_syns_ECIII: [60, 300]

kwargs:
    num_trials: 5
    seed_start: 0
    num_seeds: 1
    model_config_file_path: default_sim_config.yaml

stages:
    # might need additional stages for input resistance, f-I curve, and E:I num_syns calibration
    -   source: optimize_soma_plateaus_multi_nested.run_evaluation  # needs to be a library to look for functions
        # get_args_function - map control and gnb1 to separate workers
        compute_features: calculate_features  # a function in the source
        get_objectives: calculate_objective

optimization_title: CA1_Biophysical_TBS_Optimization

# can just comment this out to use PopulationAnnealing by default
param_gen: OptunaOptimizer
param_gen_kwargs:
    sampler: NSGAIIISampler

objective_names:
    -   total_error
    -   plateau_area_error
    -   spike_count_error
    -   trough_depol_error

x0:
    cal_gcalbar_soma:   0.007
    cal_gcalbar_trunk:  0.007
    cal_gcalbar_apical: 0.007
    cal_gcalbar_tuft:   0.007
    calH_gcalbar_soma:  0.0000316
    calH_gcalbar_trunk: 0.001455
    calH_gcalbar_apical: 0.001455
    calH_gcalbar_tuft:  0.001455
    car_gcabar_soma:    0.003
    car_gcabar_trunk:   0.00003
    car_gcabar_apical:  0.00003
    car_gcabar_tuft:    0.00003
    cat_gcatbar_soma:   0.00005
    cat_gcatbar_trunk:  0.0004
    cat_gcatbar_apical: 0.0004
    cat_gcatbar_tuft:   0.0004
    gabab_gmax:         0.00005
    num_exc_syns_CA3:   100
    num_exc_syns_ECIII: 160
    num_inh_syns_CA3:   120
    num_inh_syns_ECIII: 120
