__author__ = 'milsteina'
from specify_cells import *
from plot_results import *
import random
import sys
import scipy.signal as signal
import mkl

"""
In this version of the simulation, phase precession of CA3 inputs is implemented using the method from Chadwick et al.,
Elife, 2015, which uses a circular gaussian with a phase sensitivity factor that effectively compresses the range of
phases within each theta cycle that each input is active, which will reduce jitter across within-cycle input sequences.

These methods determine the shape of the metaplasticity function that translates plasticity signal and initial
synaptic weight to changes in synaptic weight induced by plateaus.

Assumptions:
1) Synaptic weights are all = 1 prior to field induction 1. w(t0) = 1
2) The transfer function for field induction 1 is the identity function. w(t1) = f(w(t0), s(t0)) = s(t0) * w(t0) = s(t0)
3) The transfer function for field induction 2 is a nonlinear function of plasticity signal and initial weights.
    w(t2) = f(w(t1), s(t1))
4) The plasticity signals s(t0) and s(t1) are generated by the same local and global kernels, they are just being
    interpreted differently by signaling downstream, depending on the initial synaptic weights at each input.

"""
morph_filename = 'EB2-late-bifurcation.swc'

mech_filename = '043016 Type A - km2_NMDA_KIN5_Pr'

synapses_seed = 0
num_exc_syns = 1600
num_inh_syns = 600
# allows parallel computation of multiple trials for the same spines with the same peak_locs, but with different
# input spike trains and stochastic synapses for each trial
trial_seed = 0
# .hdf5 file contains traces for position vs. time for each induction trial, and ramp vs. position for each induction
if len(sys.argv) > 1:
    cell_id = str(sys.argv[1])
else:
    cell_id = None

# experimental_filename = '112116 magee lab first induction'
# experimental_filename = '112516 magee lab first induction'
experimental_file_dir = data_dir
experimental_filename = '011717 magee lab multiple field data'

mkl.set_num_threads(2)


class History(object):
    def __init__(self):
        """

        """
        self.x = []
        self.Err = []

    def report_best(self):
        """

        :return: array
        """
        lowest_Err = min(self.Err)
        index = self.Err.index(lowest_Err)
        best_x = self.x[index]
        formatted_x = '[' + ', '.join(['%.3E' % xi for xi in best_x]) + ']'
        print 'best x: %s' % formatted_x
        print 'lowest Err: %.3E' % lowest_Err
        return best_x

    def export(self, hist_filename):
        """
        Save the history to .pkl
        """
        saved_history = {'x': self.x, 'Err': self.Err}
        write_to_pkl(data_dir+hist_filename+'.pkl', saved_history)


hist = History()


def calculate_ramp_features(ramp, induction_loc, offset=False):
    """

    :param ramp: array
    :param induction_loc: float
    :param offset: bool
    """
    extended_binned_x = np.concatenate([binned_x - track_length, binned_x, binned_x + track_length])
    smoothed_ramp = signal.savgol_filter(ramp, 19, 3, mode='wrap')
    extended_binned_ramp = np.concatenate([smoothed_ramp for i in range(3)])
    extended_interp_x = np.concatenate([default_interp_x - track_length, default_interp_x,
                                        default_interp_x + track_length])
    extended_ramp = np.interp(extended_interp_x, extended_binned_x, extended_binned_ramp)
    interp_ramp = extended_ramp[len(default_interp_x):2*len(default_interp_x)]
    min_index = np.where(interp_ramp == np.min(interp_ramp))[0][0] + len(interp_ramp)
    min_loc = extended_interp_x[min_index]
    baseline_indexes = np.where(interp_ramp <= np.percentile(interp_ramp, 10.))[0]
    baseline = np.mean(interp_ramp[baseline_indexes])
    if offset:
        interp_ramp -= baseline
        extended_ramp -= baseline
    peak_index = np.where(interp_ramp == np.max(interp_ramp))[0][0] + len(interp_ramp)
    peak_val = extended_ramp[peak_index]
    peak_x = extended_interp_x[peak_index]
    start_index = np.where(extended_ramp[:peak_index] <=
                           0.15*(peak_val - baseline) + baseline)[0][-1]
    end_index = peak_index + np.where(extended_ramp[peak_index:] <= 0.15*
                                                (peak_val - baseline) + baseline)[0][0]
    start_loc = float(start_index % len(default_interp_x)) / float(len(default_interp_x)) * track_length
    end_loc = float(end_index % len(default_interp_x)) / float(len(default_interp_x)) * track_length
    peak_shift = peak_x - induction_loc
    if peak_shift > track_length / 2.:
        peak_shift = -(track_length - peak_shift)
    elif peak_shift < -track_length / 2.:
        peak_shift += track_length
    ramp_width = extended_interp_x[end_index] - extended_interp_x[start_index]
    before_width = induction_loc - extended_interp_x[start_index]
    after_width = extended_interp_x[end_index] - induction_loc
    ratio = before_width / after_width
    return peak_val, ramp_width, peak_shift, ratio, min_loc, start_loc, end_loc


def wrap_around_and_compress(waveform, interp_x):
    """

    :param waveform: array of len(3 * interp_x)
    :param interp_x: array
    :return: array of len(interp_x)
    """
    before = np.array(waveform[:len(interp_x)])
    after = np.array(waveform[2 * len(interp_x):])
    within = np.array(waveform[len(interp_x):2 * len(interp_x)])
    waveform = within[:len(interp_x)] + before[:len(interp_x)] + after[:len(interp_x)]
    
    return waveform


def get_dynamic_theta_phase_force(phase_ranges, peak_loc, extended_x, interp_x, dx):
    """
    Expects a list of tuples containing times and phases relative to peak_loc and the non-modulated phase preference
    (zero degrees). Returns a waveform of phase vs time.
    :param phase_ranges: list of tuple (ms, degrees)
    :param peak_loc: float (cm)
    :param extended_x: array (just one item from the outer list)
    :param interp_x: array (just one item from the outer list)
    :param dx: float (cm)
    :return: :class: 'np.array'
    """
    end_x_val = phase_ranges[-1][0] + peak_loc
    start_phase_val = phase_ranges[0][1] * 2. * np.pi / 360.  # convert degrees to radians
    end_phase_val = phase_ranges[-1][1] * 2. * np.pi / 360.  # convert degrees to radians
    phase_force = np.ones_like(extended_x) * start_phase_val
    phase_force[np.where(extended_x >= end_x_val)[0]] = end_phase_val
    for i in range(len(phase_ranges) - 1):
        x0 = phase_ranges[i][0] + peak_loc
        x1 = phase_ranges[i + 1][0] + peak_loc
        phase0 = phase_ranges[i][1] * 2. * np.pi / 360.  # convert degrees to radians
        phase1 = phase_ranges[i + 1][1] * 2. * np.pi / 360.  # convert degrees to radians
        del_x = x1 - x0
        del_phase = phase1 - phase0
        if abs(del_x) > 0.:
            this_x_piece = np.arange(x0, x1 + dx / 2., dx)
            this_indexes = np.where((extended_x >= x0) & (extended_x < x1))[0]
            this_interp_x_piece = extended_x[this_indexes]
            if abs(del_phase) > 0.:
                d_phase = del_phase / del_x * dx
                this_range_piece = np.arange(phase0, phase1 + d_phase / 2., d_phase)
                this_range_interp_piece = np.interp(this_interp_x_piece, this_x_piece, this_range_piece)
            else:
                this_range_interp_piece = np.ones(len(this_interp_x_piece)) * phase0
            phase_force[this_indexes] = this_range_interp_piece
    phase_force = wrap_around_and_compress(phase_force, interp_x)
    return phase_force


def generate_generic_rate_and_phase_maps():
    """

    """
    spatial_rate_maps = []
    phase_maps = []
    for group in ['CA3']:  # stim_exc_syns:
        for i, syn in enumerate(stim_exc_syns[group]):
            peak_loc = peak_locs[group][i]
            gauss_force = excitatory_peak_rate[group] * np.exp(-((extended_x - peak_loc) / gauss_sigma)**2.)
            gauss_force = wrap_around_and_compress(gauss_force, generic_x)
            spatial_rate_maps.append(gauss_force)
            if group in excitatory_precession_range:
                phase_force = get_dynamic_theta_phase_force(excitatory_precession_range[group], peak_loc, extended_x,
                                                            generic_x, generic_dx)
                phase_maps.append(phase_force)
            
    return spatial_rate_maps, phase_maps


def generate_complete_rate_maps(simiter, induction, spatial_rate_maps, phase_maps, global_phase_offset=None):
    """

    :param simiter: int
    :param induction: int
    :param spatial_rate_maps: array
    :param phase_maps: array
    :param global_phase_offset: float
    """
    local_random.seed(simiter)
    if global_phase_offset is None:
        global_phase_offset = local_random.uniform(-np.pi, np.pi)
    complete_rate_maps = []
    running_delta_t = 0.
    for i in range(len(position[induction])):
        this_interp_t = interp_t[induction][i]
        this_interp_x = interp_x[induction][i]
        this_run_vel_gate = run_vel_gate[induction][i]
        if i == 0:
            complete_t = this_interp_t - len(this_interp_t) * dt
            complete_x = this_interp_x - track_length
            complete_run_vel_gate = np.array(this_run_vel_gate)
        else:
            complete_t = np.append(complete_t, this_interp_t + running_delta_t)
            complete_x = np.append(complete_x, this_interp_x + (i - 1) * track_length)
            complete_run_vel_gate = np.append(complete_run_vel_gate, this_run_vel_gate)
            running_delta_t += len(this_interp_t) * dt
    group = 'CA3'
    for j in range(len(spatial_rate_maps)):
        for i in range(len(position[induction])):
            this_interp_x = interp_x[induction][i]
            this_rate_map = np.interp(this_interp_x, generic_x, spatial_rate_maps[j])
            this_phase_map = np.interp(this_interp_x, generic_x, phase_maps[j])
            if i == 0:
                this_complete_rate_map = np.array(this_rate_map)
                this_complete_phase_map = np.array(this_phase_map)
            else:
                this_complete_rate_map = np.append(this_complete_rate_map, this_rate_map)
                this_complete_phase_map = np.append(this_complete_phase_map, this_phase_map)
        theta_force = np.exp(excitatory_theta_phase_tuning_factor[group] * np.cos(this_complete_phase_map +
                                                                                  excitatory_theta_phase_offset[group] -
                                                                                       2. * np.pi * complete_t /
                                                                                  global_theta_cycle_duration +
                                                                                       global_phase_offset))
        theta_force -= np.min(theta_force)
        theta_force /= np.max(theta_force)
        theta_force *= excitatory_theta_modulation_depth[group]
        theta_force += 1. - excitatory_theta_modulation_depth[group]
        this_complete_rate_map = np.multiply(this_complete_rate_map, theta_force)
        this_complete_rate_map = np.multiply(this_complete_rate_map, complete_run_vel_gate)
        complete_rate_maps.append(this_complete_rate_map)

    return complete_t, complete_x, complete_rate_maps


def generate_default_rate_maps(simiter, spatial_rate_maps, phase_maps, global_phase_offset=None):
    """

    :param simiter: int
    :param spatial_rate_maps: array
    :param phase_maps: array
    :param global_phase_offset: float
    """
    local_random.seed(simiter)
    if global_phase_offset is None:
        global_phase_offset = local_random.uniform(-np.pi, np.pi)
    default_rate_maps = []
    group = 'CA3'
    for j in range(len(spatial_rate_maps)):
        this_rate_map = np.interp(default_interp_x, generic_x, spatial_rate_maps[j])
        this_phase_map = np.interp(default_interp_x, generic_x, phase_maps[j])
        theta_force = np.exp(excitatory_theta_phase_tuning_factor[group] * np.cos(this_phase_map +
                                                                                  excitatory_theta_phase_offset[group] -
                                                                                       2. * np.pi * default_interp_t /
                                                                                  global_theta_cycle_duration +
                                                                                       global_phase_offset))
        theta_force -= np.min(theta_force)
        theta_force /= np.max(theta_force)
        theta_force *= excitatory_theta_modulation_depth[group]
        theta_force += 1. - excitatory_theta_modulation_depth[group]
        this_rate_map = np.multiply(this_rate_map, theta_force)
        default_rate_maps.append(this_rate_map)

    return default_rate_maps


def generate_complete_induction_gate(induction):
    """

    :param induction: int
    :return:
    """
    complete_induction_gate = np.array([])
    for i in range(len(position[induction])):
        this_interp_t = interp_t[induction][i]
        this_interp_x = interp_x[induction][i]
        this_induction_gate = np.zeros_like(this_interp_t)
        this_induction_loc = induction_locs[induction][i]
        this_induction_dur = induction_durs[induction][i]
        if this_induction_loc is not None:
            start_index = np.where(this_interp_x >= this_induction_loc)[0][0]
            end_index = start_index + int(this_induction_dur / dt)
            this_induction_gate[start_index:end_index] = 1.
        complete_induction_gate = np.append(complete_induction_gate, this_induction_gate)

    return complete_induction_gate


def subtract_baseline(waveform, baseline=None):
    """

    :param waveform: array
    :param baseline: float
    :return: array
    """
    if baseline is None:
        baseline = np.mean(waveform[np.where(np.array(waveform) <= np.percentile(waveform, 10.))[0]])
    waveform -= baseline
    return baseline


def get_expected_depolarization(rate_maps, weights, interp_x):
    """
    Take pre-computed rate maps and weights for a set of inputs. Convolve with an EPSP kernel, sum, normalize, and
    downsample to 100 spatial bins.
    :param rate_maps: list of array
    :param weights: list of float
    :param interp_x: array (just one item from the outer list)
    :return: array
    """
    filter_t = np.arange(0., 200., dt)
    epsp_filter = np.exp(-filter_t/20.) - np.exp(-filter_t/.5)
    epsp_filter /= np.sum(epsp_filter)
    weighted_rate_maps = []
    scaling_factor = 7.15e-4  # generates a predicted 6 mV depolarization from gaussian weights with peak = 2.5
    for i, rate_map in enumerate(rate_maps):
        this_weighted_rate_map = rate_map * weights[i] * scaling_factor
        this_weighted_rate_map = np.concatenate([this_weighted_rate_map for i in range(3)])
        this_weighted_rate_map = np.convolve(this_weighted_rate_map, epsp_filter)[:3*len(interp_x)]
        weighted_rate_maps.append(this_weighted_rate_map)
    expected_depolarization = np.sum(weighted_rate_maps, axis=0)
    expected_depolarization = low_pass_filter(expected_depolarization, 2.,
                                              3*len(interp_x)*dt, dt, 1.)[len(interp_x): 2 * len(interp_x)]
    expected_depolarization = np.interp(binned_x, interp_x, expected_depolarization)
    return expected_depolarization


NMDA_type = 'NMDA_KIN5'

dt = 1.  # ms
down_dt = 10.  # ms, to speed up optimization
equilibrate = 250.  # time to steady-state
global_theta_cycle_duration = 150.  # -0.5 * run_vel + 155.  # (ms)
input_field_width = 90.  # cm

position = {}
ramp = {}
induction_locs = {}
induction_durs = {}
t = {}
interp_t = {}
interp_x = {}
run_vel = {}
run_vel_gate = {}

if cell_id is not None:
    with h5py.File(experimental_file_dir+experimental_filename+'.hdf5', 'r') as f:
        track_length = f[cell_id].attrs['track_length']
        binned_dx = track_length / 100.  # cm
        binned_x = np.arange(0., track_length + binned_dx / 2., binned_dx)[:100] + binned_dx / 2.
        for induction in f[cell_id]:
            induction_locs[int(induction)] = []
            induction_durs[int(induction)] = []
            if 'position' in f[cell_id][induction]:
                sampling_rate = f[cell_id][induction].attrs['sampling_rate']
                position_dt = 1000. / sampling_rate  # convert s to ms
                position[int(induction)] = []
                t[int(induction)] = []
                induction_locs[int(induction)].append(None)
                induction_durs[int(induction)].append(None)
                for trial in f[cell_id][induction]['position'].itervalues():
                    this_position = np.array(trial) / np.max(trial) * track_length
                    position[int(induction)].append(this_position)
                    t[int(induction)].append(
                        np.arange(0., len(this_position)*position_dt, position_dt)[:len(this_position)])
                    induction_locs[int(induction)].append(trial.attrs['induction_loc'])
                    induction_durs[int(induction)].append(trial.attrs['induction_dur'])
                if 'pre_position' in f[cell_id][induction]:
                    for i, trial in enumerate(f[cell_id][induction]['pre_position'].itervalues()):
                        this_position = np.array(trial) / np.max(trial) * track_length
                        position[int(induction)].insert(i, this_position)
                        t[int(induction)].insert(i,
                            np.arange(0., len(this_position) * position_dt, position_dt)[:len(this_position)])
                else:
                    position[int(induction)].insert(0, position[int(induction)][0])
                    t[int(induction)].insert(0, t[int(induction)][0])
                if 'post_position' in f[cell_id][induction]:
                    for trial in f[cell_id][induction]['post_position'].itervalues():
                        this_position = np.array(trial) / np.max(trial) * track_length
                        position[int(induction)].append(this_position)
                        t[int(induction)].append(
                            np.arange(0., len(this_position) * position_dt, position_dt)[:len(this_position)])
                else:
                    position[int(induction)].append(position[int(induction)][-1])
                    t[int(induction)].append(t[int(induction)][-1])
                induction_locs[int(induction)].append(None)
                induction_durs[int(induction)].append(None)
            ramp[int(induction)] = signal.savgol_filter(f[cell_id][induction]['ramp'][:], 19, 4, mode='wrap')
            # Placeholder induction_loc for pre-existing place fields (no first induction)
            if int(induction) not in position:
                peak_index = np.where(ramp[int(induction)] == np.max(ramp[int(induction)]))[0][0]
                this_induction_loc = binned_x[peak_index] + 10.
                if this_induction_loc > track_length:
                    this_induction_loc -= track_length
                induction_locs[int(induction)].append(this_induction_loc)
            """
            plt.plot(binned_x, f[cell_id][induction]['ramp'], binned_x, ramp[int(induction)])
            plt.title(induction)
            plt.show()
            plt.close()
            """
else:
    raise Exception('No data imported')


generic_dx = binned_dx / 100.  # cm
generic_x = np.arange(0., track_length, generic_dx)

default_run_vel = 30.  # cm/s
generic_position_dt = generic_dx / default_run_vel * 1000.
generic_t = np.arange(0., len(generic_x)*generic_position_dt, generic_position_dt)[:len(generic_x)]
generic_track_duration = len(generic_t) * generic_position_dt

default_interp_t = np.arange(0., generic_t[-1], dt)
default_interp_x = np.interp(default_interp_t, generic_t, generic_x)

extended_x = np.concatenate([generic_x - track_length, generic_x, generic_x + track_length])

vel_window_dur = 10.  # ms
vel_window_bins = int(vel_window_dur/dt)/2

for induction in position:
    interp_t[induction] = []
    interp_x[induction] = []
    run_vel[induction] = []
    run_vel_gate[induction] = []
    for i in range(len(position[induction])):
        this_interp_t = np.arange(0., t[induction][i][-1] + dt / 2., dt)
        interp_t[induction].append(this_interp_t)
        this_interp_x = np.interp(interp_t[induction][i], t[induction][i], position[induction][i])
        interp_x[induction].append(this_interp_x)
        padded_t = np.insert(this_interp_t, 0, this_interp_t[-vel_window_bins:] - this_interp_t[-1] - dt)
        padded_t = np.append(padded_t, this_interp_t[:vel_window_bins + 1] + this_interp_t[-1] + dt)
        padded_x = np.insert(this_interp_x, 0, this_interp_x[-vel_window_bins:] - track_length)
        padded_x = np.append(padded_x, this_interp_x[:vel_window_bins + 1] + track_length)
        this_run_vel = []
        for j in range(vel_window_bins, vel_window_bins+len(this_interp_x)):
            this_run_vel.append(np.sum(np.diff(padded_x[j - vel_window_bins:j + vel_window_bins + 1])) /
                                np.sum(np.diff(padded_t[j - vel_window_bins:j + vel_window_bins + 1])) * 1000.)
        this_run_vel = np.array(this_run_vel)
        this_run_vel_gate = np.zeros_like(this_run_vel)
        this_run_vel_gate[np.where(this_run_vel>5.)[0]] = 1.
        run_vel[induction].append(this_run_vel)
        run_vel_gate[induction].append(this_run_vel_gate)


track_equilibrate = 2. * global_theta_cycle_duration
track_duration = {induction:
                      [interp_t[induction][i][-1] for i in range(len(position[induction]))] for induction in position}

excitatory_peak_rate = {'CA3': 40., 'ECIII': 40.}
excitatory_theta_modulation_depth = {'CA3': 0.7, 'ECIII': 0.7}
# From Chadwick et al., ELife 2015
excitatory_theta_phase_tuning_factor = {'CA3': 0.8, 'ECIII': 0.8}
excitatory_precession_range = {}  # # (ms, degrees)
excitatory_precession_range['CA3'] = [(-input_field_width*0.7, 0.), (-input_field_width*0.6, 180.),
                                      (-input_field_width*0.35, 180.), (input_field_width*0.35, -180.),
                                      (input_field_width*0.6, -180.), (input_field_width*0.7, 0.)]
excitatory_theta_phase_offset = {}
excitatory_theta_phase_offset['CA3'] = 165. / 360. * 2. * np.pi  # radians
excitatory_theta_phase_offset['ECIII'] = 0. / 360. * 2. * np.pi  # radians
excitatory_stochastic = 1

v_init = -67.

syn_types = ['AMPA_KIN', NMDA_type]

local_random = random.Random()

# choose a subset of synapses to stimulate with inhomogeneous poisson rates
local_random.seed(synapses_seed)

cell = CA1_Pyr(morph_filename, mech_filename, full_spines=True)

trunk_bifurcation = [trunk for trunk in cell.trunk if cell.is_bifurcation(trunk, 'trunk')]
if trunk_bifurcation:
    trunk_branches = [branch for branch in trunk_bifurcation[0].children if branch.type == 'trunk']
    # get where the thickest trunk branch gives rise to the tuft
    trunk = max(trunk_branches, key=lambda node: node.sec(0.).diam)
    trunk = (node for node in cell.trunk if cell.node_in_subtree(trunk, node) and 'tuft' in (child.type
                                                                                    for child in node.children)).next()
else:
    trunk_bifurcation = [node for node in cell.trunk if 'tuft' in (child.type for child in node.children)]
    trunk = trunk_bifurcation[0]

all_exc_syns = {sec_type: [] for sec_type in ['basal', 'trunk', 'apical', 'tuft']}
stim_exc_syns = {'CA3': [], 'ECIII': []}
stim_successes = []
peak_locs = {'CA3': [], 'ECIII': []}

# place synapses in trunk for inheritance of mechanisms (for testing)
if 'trunk' not in all_exc_syns:
    for node in cell.trunk:
        for spine in node.spines:
            syn = Synapse(cell, spine, syn_types, stochastic=excitatory_stochastic)

# place synapses in every spine
for sec_type in all_exc_syns:
    for node in cell.get_nodes_of_subtype(sec_type):
        for spine in node.spines:
            syn = Synapse(cell, spine, syn_types, stochastic=excitatory_stochastic)
            all_exc_syns[sec_type].append(syn)
# cell.init_synaptic_mechanisms()

# get the fraction of total spines contained in each sec_type
total_exc_syns = {sec_type: len(all_exc_syns[sec_type]) for sec_type in ['basal', 'trunk', 'apical', 'tuft']}
fraction_exc_syns = {sec_type: float(total_exc_syns[sec_type]) / float(np.sum(total_exc_syns.values())) for sec_type in
                 ['basal', 'trunk', 'apical', 'tuft']}

for sec_type in all_exc_syns:
    for i in local_random.sample(range(len(all_exc_syns[sec_type])), int(num_exc_syns*fraction_exc_syns[sec_type])):
        syn = all_exc_syns[sec_type][i]
        if sec_type == 'tuft':
            stim_exc_syns['ECIII'].append(syn)
        else:
            stim_exc_syns['CA3'].append(syn)

gauss_sigma = input_field_width / 3. / np.sqrt(2.)  # contains 99.7% gaussian area

delta_peak_locs = {}
extended_peak_locs = {}
within_track = {}
for group in stim_exc_syns:
    delta_peak_locs[group] = track_length / len(stim_exc_syns[group])
    if stim_exc_syns[group]:
        extended_peak_locs[group] = np.arange(-track_length, 2. * track_length, delta_peak_locs[group])
        within_track[group] = np.where((extended_peak_locs[group] >= 0.) &
                                       (extended_peak_locs[group] < track_length))[0]
        peak_locs[group] = extended_peak_locs[group][within_track[group]]

for group in stim_exc_syns:
    for syn in stim_exc_syns[group]:
        all_exc_syns[syn.node.parent.parent.type].remove(syn)

default_global_phase_offset = 0.

spatial_rate_maps, phase_maps = generate_generic_rate_and_phase_maps()


complete_t, complete_x, complete_rate_maps, complete_induction_gates = {}, {}, {}, {}
for induction in position:
    complete_t[induction], complete_x[induction], complete_rate_maps[induction] = \
        generate_complete_rate_maps(trial_seed, induction, spatial_rate_maps, phase_maps, default_global_phase_offset)
    complete_induction_gates[induction] = generate_complete_induction_gate(induction)

default_rate_maps = generate_default_rate_maps(trial_seed, spatial_rate_maps, phase_maps, default_global_phase_offset)

baseline = None
for induction in ramp:
    if baseline is None:
        ramp_baseline_indexes = np.where(np.array(ramp[induction]) <= np.percentile(ramp[induction], 10.))[0]
        baseline = np.mean(ramp[induction][ramp_baseline_indexes])
    ignore = subtract_baseline(ramp[induction], baseline)

"""
for induction in ramp:
    plt.plot(binned_x, ramp[induction], label=induction)
plt.legend(loc='best', frameon=False, framealpha=0.5)
plt.ylabel('Ramp depolarization (mV)')
plt.xlabel('Position (cm)')
plt.title('Experimental ramps')
plt.show()
plt.close()
"""

def check_bounds(x, xmin, xmax):
    """
    Check that the current set of parameters are within the specified bounds.
    :param x: array
    :param xmin: array
    :param xmax: array
    :return: bool
    """
    for i in range(len(x)):
        if ((xmin[i] is not None and x[i] < xmin[i]) or
                (xmax[i] is not None and x[i] > xmax[i])):
            return False
    return True


def build_kernels(x, plot=False):
    """
    Construct two kernels with exponential rise and decay:
    1) Local kernel that generates a plasticity signal at each spine
    2) Global kernal that generates a plasticity signal during dendritic calcium spiking
    :param x: array: [local_rise_tau, local_decay_tau, global_rise_tau, global_decay_tau, filter_ratio, global_scale]
    :param plot: bool
    :return: array, array
    """
    local_rise_tau = x[0]
    local_decay_tau = x[1]
    global_rise_tau = x[2]
    global_decay_tau = x[3]
    filter_ratio = x[4]

    max_time_scale = np.max([local_rise_tau+local_decay_tau, global_rise_tau+global_decay_tau])
    filter_t = np.arange(0., 6.*max_time_scale, dt)
    local_filter = np.exp(-filter_t/local_decay_tau) - np.exp(-filter_t/local_rise_tau)
    peak_index = np.where(local_filter == np.max(local_filter))[0][0]
    decay_indexes = np.where(local_filter[peak_index:] < 0.005*np.max(local_filter))[0]
    if np.any(decay_indexes):
        local_filter = local_filter[:peak_index+decay_indexes[0]]
    local_filter /= np.sum(local_filter)

    global_filter = np.exp(-filter_t / global_decay_tau) - np.exp(-filter_t / global_rise_tau)
    peak_index = np.where(global_filter == np.max(global_filter))[0][0]
    decay_indexes = np.where(global_filter[peak_index:] < 0.005 * np.max(global_filter))[0]
    if np.any(decay_indexes):
        global_filter = global_filter[:peak_index + decay_indexes[0]]
    global_filter /= np.sum(global_filter)

    if plot:
        fig, axes = plt.subplots(1)
        axes.plot(filter_t[:len(local_filter)], local_filter / np.max(local_filter), color='g',
                  label='Local plasticity kernel')
        axes.plot(filter_t[:len(global_filter)], global_filter / np.max(global_filter) * filter_ratio, color='k',
                  label='Global plasticity kernel')
        axes.legend(loc='best', frameon=False, framealpha=0.5)
        axes.set_xlabel('Time (ms)')
        axes.set_ylabel('Relative kernel amplitude (a.u.)')
        axes.set_xlim(-500., max(5000., max(filter_t[:len(local_filter)][-1], filter_t[:len(global_filter)][-1])))
        clean_axes(axes)
        plt.show()
        plt.close()

    return local_filter, global_filter


def calculate_plasticity_signal(x, local_kernel, global_kernel, induction, plot=False):
    """
    Given the local and global kernels, convolve each input rate_map with the local kernel, and convolve the
    current injection with the global kernel. The weight change for each input is proportional to the area under the
    product of the two signals. Incremental weight changes accrue across multiple induction trials.
    :param x: array: [local_rise_tau, local_decay_tau, global_rise_tau, global_decay_tau, filter_ratio, kernel_scale]
    :param local_kernel: array
    :param global_kernel: array
    :param induction: int: key for dicts of arrays
    :param plot: bool
    :return: plasticity_signal: array
    """
    saturation_factor = 0.02
    filter_ratio = x[4]
    kernel_scale = x[5]
    group = 'CA3'
    for attempt in range(2):
        plasticity_signal = np.zeros_like(peak_locs[group])
        max_local_signal = 0.
        max_global_signal = 0.
        start_time = time.time()
        global_signal = np.convolve(complete_induction_gates[induction], global_kernel)[:len(complete_t[induction])] * \
                        kernel_scale
        down_t = np.arange(complete_t[induction][0], complete_t[induction][-1] + down_dt / 2., down_dt)
        global_signal = np.interp(down_t, complete_t[induction], global_signal)
        max_global_signal = max(max_global_signal, np.max(global_signal))
        filter_t = np.arange(0., len(local_kernel) * dt, dt)
        down_filter_t = np.arange(0., filter_t[-1] + down_dt / 2., down_dt)
        local_kernel_down = np.interp(down_filter_t, filter_t, local_kernel)
        for j, stim_force in enumerate(complete_rate_maps[induction]):
            this_stim_force = np.interp(down_t, complete_t[induction], stim_force)
            local_signal = np.convolve(0.001 * down_dt * this_stim_force, local_kernel_down)[:len(down_t)] / \
                           saturation_factor * kernel_scale / filter_ratio
            max_local_signal = max(max_local_signal, np.max(local_signal))
            this_signal = np.minimum(local_signal, global_signal)
            this_area = np.trapz(this_signal, dx=down_dt)
            plasticity_signal[j] += this_area
            if plot and j == int(len(complete_rate_maps[induction])/2) and attempt == 1:
                ylim = max(np.max(local_signal), np.max(global_signal))
                start_index = np.where(interp_x[induction][1] >= induction_locs[induction][1])[0][0]
                this_induction_start = interp_t[induction][1][start_index]
                this_induction_dur = induction_durs[induction][1]
                start_time = -5000.
                end_time = interp_t[induction][1][-1] + 5000.
                this_duration = end_time - start_time
                x_start = (5000. + this_induction_start) / this_duration
                x_end = (5000. + this_induction_start + this_induction_dur) / this_duration
                fig, axes = plt.subplots(1)
                axes.plot(down_t/1000., local_signal, label='Local signal', color='g')
                axes.plot(down_t/1000., global_signal, label='Global signal', color='k')
                axes.fill_between(down_t/1000., 0., this_signal, label='Overlap', facecolor='r', alpha=0.5)
                axes.axhline(y=ylim*1.05, xmin=x_start, xmax=x_end, linewidth=3, c='k')
                axes.legend(loc='best', frameon=False, framealpha=0.5)
                axes.set_xlabel('Time (s)')
                axes.set_ylabel('Signal amplitude (a.u.)')
                axes.set_xlim(-5., interp_t[induction][1][-1]/1000. + 5.)
                axes.set_ylim(-0.05*ylim, ylim*1.1)
                axes.set_title('Induced plasticity signal')
                clean_axes(axes)
                plt.show()
                plt.close()
        saturation_factor *= filter_ratio * max_local_signal / max_global_signal
        # print 'saturation factor after attempt %i: %.3E' % (attempt, saturation_factor)
        # print 'Computed weights in %i s' % (time.time() - start_time)

    if plot:
        mean_induction_locs = np.mean([induction_loc for induction_loc in induction_locs[induction] if
                                       induction_loc is not None])
        x_start = mean_induction_locs / track_length
        ylim = np.max(plasticity_signal) + 1.
        fig, axes = plt.subplots(1)
        axes.scatter(peak_locs['CA3'], plasticity_signal+1., color='k')
        axes.axhline(y=ylim + 0.1, xmin=x_start, xmax=x_start + 0.02, linewidth=3, c='k')
        axes.set_ylabel('Relative synaptic weight')
        axes.set_xlabel('Location (cm)')
        axes.set_xlim(0., track_length)
        axes.set_title('Induced synaptic weight distribution')
        clean_axes(axes)
        plt.show()
        plt.close()

    return plasticity_signal


def ramp_error_cont(x, xmin, xmax, ramp, induction=None, baseline=None, plot=False, full_output=False):
    """
    Calculates a rule_waveform and set of weights to match the first place field induction.
    :param x: array [local_rise_tau, local_decay_tau, global_rise_tau, global_decay_tau, filter_ratio, kernel_scale]
    :param xmin: array
    :param xmax: array
    :param ramp: array
    :param induction: int: key for dicts of arrays
    :param baseline: float
    :param plot: bool
    :param full_output: bool: whether to return all relevant objects (True), or just Err (False)
    :return: float
    """
    formatted_x = '[' + ', '.join(['%.3f' % xi for xi in x]) + ']'
    print 'Trying x: %s for cell %s, induction %i' % (formatted_x, cell_id, induction)
    if not check_bounds(x, xmin, xmax):
        print 'Aborting: Invalid parameter values.'
        return 1e9
    elif x[3] <= x[2]:
        print 'Aborting: Invalid parameter values.'
        return 1e9
    start_time = time.time()
    if induction is None:
        induction = 1
    local_kernel, global_kernel = build_kernels(x, plot)
    this_weights = calculate_plasticity_signal(x, local_kernel, global_kernel, induction, plot)
    model_ramp = get_expected_depolarization(default_rate_maps, this_weights + 1., default_interp_x)
    if baseline is None:
        model_baseline = subtract_baseline(model_ramp)
    else:
        model_baseline = baseline
        model_ramp -= model_baseline
    amp, width, peak_shift, ratio, min_loc = {}, {}, {}, {}, {}
    this_induction_loc = np.mean([induction_loc for induction_loc in induction_locs[induction] if
                                       induction_loc is not None])
    for this_ramp, this_key in zip((ramp, model_ramp), ('exp', 'model')):
        amp[this_key], width[this_key], peak_shift[this_key], ratio[this_key], min_loc[this_key], start_loc, end_loc = \
            calculate_ramp_features(this_ramp, this_induction_loc)
    Err = 0.
    for feature, sigma in zip((amp, width, peak_shift, ratio), (0.01, 0.1, 0.05, 0.05)):
        Err_piece = ((feature['exp'] - feature['model']) / sigma) ** 2.
        # print Err_piece
        Err += Err_piece
    delta_min = abs(min_loc['exp'] - min_loc['model'])
    if delta_min > track_length / 2.:
        delta_min = track_length - delta_min
    Err += (delta_min / 0.05) ** 2.

    for j in range(len(ramp)):
        Err += ((ramp[j] - model_ramp[j]) / 0.1) ** 2.

    # penalize DC drifts in minimum weight
    Err += (np.min(this_weights)/0.005) ** 2.

    if plot:
        x_start = this_induction_loc/track_length
        ylim = max(np.max(ramp), np.max(model_ramp))
        ymin = min(np.min(ramp), np.min(model_ramp))
        fig, axes = plt.subplots(1)
        axes.plot(binned_x, ramp, label='Experiment', color='r')
        axes.plot(binned_x, model_ramp, label='Model', color='k')
        axes.axhline(y=ylim + 0.1, xmin=x_start, xmax=x_start + 0.02, linewidth=3, c='r')
        axes.set_xlabel('Location (cm)')
        axes.set_ylabel('Depolarization (mV)')
        axes.set_xlim([0., track_length])
        axes.set_ylim([math.floor(ymin) - 0.5, math.ceil(ylim) + 0.5])
        axes.legend(loc='best', frameon=False, framealpha=0.5)
        axes.set_title('Induced Vm depolarization')
        clean_axes(axes)
        plt.show()
        plt.close()

    formatted_x = '[' + ', '.join(['%.4f' % xi for xi in x]) + ']'
    print 'x: %s, Err: %.4E took %i s' % (formatted_x, Err, time.time()-start_time)
    print 'exp: amp: %.1f, ramp_width: %.1f, peak_shift: %.1f, asymmetry: %.1f, min_loc: %.1f' % \
          (amp['exp'], width['exp'], peak_shift['exp'], ratio['exp'], min_loc['exp'])
    print 'model: amp: %.1f, ramp_width: %.1f, peak_shift: %.1f, asymmetry: %.1f, min_loc: %.1f' % \
          (amp['model'], width['model'], peak_shift['model'], ratio['model'], min_loc['model'])
    sys.stdout.flush()
    if full_output:
        return local_kernel, global_kernel, this_weights, model_ramp, model_baseline
    else:
        hist.x.append(x)
        hist.Err.append(Err)
        return Err


def ramp_error_ignore_kernel(x, xmin, xmax, ramp, induction=None, baseline=None, plot=False, full_output=False):
    """
    Calculates an arbitrary set of weights to match a place field ramp, agnostic about underlying kernel or induction
    order.
    :param x: array [11 binned synaptic weights]
    :param xmin: array
    :param xmax: array
    :param ramp: array
    :param induction: int: key for dicts of arrays
    :param baseline: float
    :param plot: bool
    :param full_output: bool: whether to return all relevant objects (True), or just Err (False)
    :return: float
    """
    formatted_x = '[' + ', '.join(['%.3f' % xi for xi in x]) + ']'
    print 'Trying x: %s for cell %s, induction %i' % (formatted_x, cell_id, induction)
    if not check_bounds(x, xmin, xmax):
        print 'Aborting: Invalid parameter values.'
        return 1e9
    start_time = time.time()
    if induction is None:
        induction = 1
    binned_weights_dx = track_length / (len(x) - 1)
    binned_weights_x = np.arange(0., track_length + binned_weights_dx / 2., binned_weights_dx)
    interp_weights = np.interp(peak_locs['CA3'], binned_weights_x, x)
    smooth_weights = signal.savgol_filter(interp_weights, 701, 3, mode='wrap')
    model_ramp = get_expected_depolarization(default_rate_maps, smooth_weights, default_interp_x)
    if baseline is None:
        model_baseline = subtract_baseline(model_ramp)
    else:
        model_baseline = baseline
        model_ramp -= model_baseline
    amp, width, peak_shift, ratio, min_loc = {}, {}, {}, {}, {}
    this_induction_loc = np.mean([induction_loc for induction_loc in induction_locs[induction] if
                                  induction_loc is not None])
    for this_ramp, this_key in zip((ramp, model_ramp), ('exp', 'model')):
        amp[this_key], width[this_key], peak_shift[this_key], ratio[this_key], min_loc[this_key], start_loc, end_loc = \
            calculate_ramp_features(this_ramp, this_induction_loc)
    print 'induction_loc: %.1f, start_loc: %.1f, end_loc: %.1f' % (this_induction_loc, start_loc, end_loc)
    asymmetry = np.zeros_like(peak_locs['CA3'])
    start_index = int(start_loc/track_length*len(peak_locs['CA3']))
    induction_index = int(this_induction_loc/track_length*len(peak_locs['CA3']))
    end_index = int(end_loc/track_length*len(peak_locs['CA3']))
    if start_loc > this_induction_loc:
        asymmetry[start_index:] = 1.
        asymmetry[:induction_index] = 1.
        asymmetry[induction_index:end_index] = 2.
    else:
        asymmetry[start_index:induction_index] = 1.
        if end_loc > this_induction_loc:
            asymmetry[induction_index:end_index] = 2.
        else:
            asymmetry[:end_index] = 2.
            asymmetry[induction_index:] = 2.
    Err = 0.
    for feature, sigma in zip((amp, width, peak_shift, ratio), (0.01, 0.1, 0.05, 0.05)):
        Err += ((feature['exp'] - feature['model']) / sigma) ** 2.
    delta_min = abs(min_loc['exp'] - min_loc['model'])
    if delta_min > track_length / 2.:
        delta_min = track_length - delta_min
    Err += (delta_min / 0.05) ** 2.

    for j in range(len(ramp)):
        Err += ((ramp[j] - model_ramp[j]) / 0.1) ** 2.

    Err += ((np.min(ramp) - np.min(model_ramp)) / 0.01) ** 2.

    # penalize DC drifts in minimum weight
    if induction == 1:
        Err += (np.min(smooth_weights - 1.)/0.005) ** 2.

    # penalize large jumps in weights
    Err += (np.sum(np.abs(np.diff(x)))/0.1) ** 2.

    if plot:
        x_start = this_induction_loc/track_length
        ylim = max(np.max(ramp), np.max(model_ramp))
        ymin = min(np.min(ramp), np.min(model_ramp))
        fig, axes = plt.subplots(1)
        axes.plot(binned_x, ramp, label='Experiment', color='r')
        axes.plot(binned_x, model_ramp, label='Model', color='k')
        axes.axhline(y=ylim + 0.1, xmin=x_start, xmax=x_start + 0.02, linewidth=3, c='r')
        axes.set_xlabel('Location (cm)')
        axes.set_ylabel('Depolarization (mV)')
        axes.set_xlim([0., track_length])
        axes.set_ylim([math.floor(ymin) - 0.5, math.ceil(ylim) + 0.5])
        axes.legend(loc='best', frameon=False, framealpha=0.5)
        axes.set_title('Induced Vm depolarization')
        clean_axes(axes)
        plt.show()
        plt.close()
        fig, axes = plt.subplots(1)
        axes.plot(peak_locs['CA3'], smooth_weights)
        axes.set_xlabel('Location (cm)')
        axes.set_ylabel('Candidate synaptic weights')
        clean_axes(axes)
        plt.show()
        plt.close()

    formatted_x = '[' + ', '.join(['%.4f' % xi for xi in x]) + ']'
    print 'x: %s, Err: %.4E took %i s' % (formatted_x, Err, time.time()-start_time)
    print 'exp: amp: %.1f, ramp_width: %.1f, peak_shift: %.1f, asymmetry: %.1f, min_loc: %.1f, min_val: %.1f' % \
          (amp['exp'], width['exp'], peak_shift['exp'], ratio['exp'], min_loc['exp'], np.min(ramp))
    print 'model: amp: %.1f, ramp_width: %.1f, peak_shift: %.1f, asymmetry: %.1f, min_loc: %.1f, min_val: %.1f' % \
          (amp['model'], width['model'], peak_shift['model'], ratio['model'], min_loc['model'], np.min(model_ramp))
    sys.stdout.flush()
    if full_output:
        return smooth_weights, model_ramp, model_baseline, asymmetry
    else:
        hist.x.append(x)
        hist.Err.append(Err)
        return Err


def optimize_polish(x, xmin, xmax, error_function, ramp, induction=None, baseline=None, maxfev=None):
    """

    :param x: array
    :param xmin: array
    :param xmax: array
    :param error_function: callable
    :param ramp: array
    :param induction: int: key for dicts of arrays
    :param baseline: float
    :param maxfev: int
    :return: dict
    """
    if maxfev is None:
        maxfev = 400

    result = optimize.minimize(error_function, x, method='Nelder-Mead', options={'ftol': 1e-3,
                                                    'xtol': 1e-3, 'disp': True, 'maxiter': maxfev},
                               args=(xmin, xmax, ramp, induction, baseline))
    formatted_x = '['+', '.join(['%.3E' % xi for xi in result.x])+']'
    print 'Process: %i completed optimize_polish for cell %s, induction %i after %i iterations with Error: %.4E and ' \
          'x: %s' % (os.getpid(), cell_id, induction, result.nit, result.fun, formatted_x)
    return {'x': result.x, 'Err': result.fun}


def optimize_seqls(x, xmin, xmax, error_function, ramp, induction=None, baseline=None, maxfev=None):
    """

    :param x: array
    :param xmin: array
    :param xmax: array
    :param error_function: callable
    :param ramp: array
    :param induction: int: key for dicts of arrays
    :param baseline: float
    :param maxfev: int
    :return: dict
    """
    if maxfev is None:
        maxfev = 700

    bounds = [(xmin_i, xmax_i) for xmin_i, xmax_i in zip(xmin, xmax)]

    result = optimize.minimize(error_function, x, method='SLSQP', options={'ftol': 1e-3, 'disp': True,
                                                                               'maxiter': maxfev}, bounds=bounds,
                               args=(ramp, induction, baseline))
    formatted_x = '[' + ', '.join(['%.3E' % xi for xi in result.x]) + ']'
    print 'Process: %i completed optimize_seqls for cell %s, induction %i after %i iterations with Error: %.4E ' \
          'and x: %s' % (os.getpid(), cell_id, induction, result.nit, result.fun, formatted_x)
    return {'x': result.x, 'Err': result.fun}


def optimize_explore(x, xmin, xmax, error_function, ramp, induction=None, baseline=None, maxfev=None):
    """

    :param x: array
    :param xmin: array
    :param xmax: array
    :param error_function: callable
    :param ramp: array
    :param induction: int: key for dicts of arrays
    :param baseline: float
    :param maxfev: int
    :return: dict
    """
    if maxfev is None:
        maxfev = 700

    take_step = Normalized_Step(x, xmin, xmax)
    minimizer_kwargs = dict(method=null_minimizer, args=(xmin, xmax, ramp, induction, baseline))
    result = optimize.basinhopping(error_function, x, niter=maxfev, niter_success=maxfev/2,
                                   disp=True, interval=min(20, int(maxfev/20)), minimizer_kwargs=minimizer_kwargs,
                                   take_step=take_step)
    formatted_x = '['+', '.join(['%.3E' % xi for xi in result.x])+']'
    print 'Process: %i completed optimize_explore for cell %s, induction %i after %i iterations with Error: %.4E ' \
          'and x: %s' % (os.getpid(), cell_id, induction, result.nit, result.fun, formatted_x)
    return {'x': result.x, 'Err': result.fun}


local_kernel = {}
global_kernel = {}
plasticity_signal = {}
weights = {}
model_ramp = {}
model_baseline = {}
asymmetry = {}

x0 = {}

# x0['1'] = [1.741E+01, 1.167E+03, 4.960E+01, 2.717E+02, 1.000E+00, 2.822E-03]  # Error: 1.007E+05 * cell1
# x0['1'] = [1.732E+01, 1.169E+03, 5.054E+01, 2.728E+02, 1.002E+00, 2.822E-03]  # Error: 1.0074E+05 * cell1
x0['1'] = [1.907E+01, 1.168E+03, 5.378E+01, 2.813E+02, 1.000E+00, 2.818E-03]  # Error: 1.0811E+05 * cell1
# x0['2'] = [4.699E+02, 5.102E+02, 1.850E+01, 1.765E+02, 1.500E+00, 1.855E-03]  # Error: 6.294E+04 * cell15
# x0['2'] = [4.851E+02, 5.273E+02, 1.006E+01, 2.199E+02, 1.474E+00, 1.800E-03]  # Error: 5.4097E+04 * cell15
x0['2'] = [4.769E+02, 5.342E+02, 1.000E+01, 2.212E+02, 1.463E+00, 1.826E-03]  # Error: 1.3157E+04 * cell15
# x0['3'] = [3.006E+02, 2.072E+03, 2.326E+01, 7.880E+02, 1.500E+00, 1.959E-03]  # Error:
# x0['3'] = [2.138E+02, 1.616E+03, 1.643E+01, 1.005E+03, 1.494E+00, 1.936E-03]  # Error: 2.308E+05 * cell7
# x0['3'] = [2.138E+02, 1.614E+03, 1.646E+01, 1.002E+03, 1.500E+00, 1.955E-03]  # Error: 2.3074E+05 * cell7
x0['3'] = [3.656E+02, 1.068E+03, 7.596E+01, 9.424E+02, 1.481E+00, 1.873E-03]  # Error: 2.1695E+05 * cell7
# x0['4'] = [8.912E+01, 1.651E+03, 1.137E+01, 1.220E+03, 7.057E-01, 1.663E-03]  # Error:
# x0['4'] = [1.681E+02, 1.788E+03, 2.410E+01, 1.697E+03, 1.002E+00, 2.042E-03]  # Error: 9.6546E+04 * cell9
# x0['4'] = [1.729E+02, 1.961E+03, 2.326E+01, 1.723E+03, 1.000E+00, 2.052E-03]  # Error: 8.7946E+04 * cell9
x0['4'] = [1.731E+02, 1.958E+03, 2.330E+01, 1.723E+03, 1.000E+00, 2.094E-03]  # Error: 1.0521E+05 * cell9
# x0['5'] = [4.820E+02, 6.828E+02, 1.000E+01, 1.565E+02, 1.418E+00, 1.474E-03]  # Error:
# x0['5'] = [3.747E+02, 8.444E+02, 1.338E+01, 4.710E+02, 1.500E+00, 1.510E-03]  # Error: 5.8753E+04 * cell5
# x0['5'] = [3.452E+02, 7.208E+02, 1.000E+01, 4.004E+02, 1.500E+00, 1.474E-03]  # Error: 6.2414E+04 * cell5
x0['5'] = [3.778E+02, 7.870E+02, 2.342E+01, 5.514E+02, 1.500E+00, 1.540E-03]  # Error: 2.7011E+04 * cell5
# x0['6'] = [1.260E+02, 1.109E+03, 4.557E+01, 1.682E+03, 1.402E+00, 7.828E-04]  # Error:
# x0['6'] = [1.075E+02, 2.395E+03, 2.360E+02, 2.373E+02, 1.436E+00, 9.375E-04]  # Error: 1.622E+05 * cell4
# x0['6'] = [7.717E+01, 2.574E+03, 2.526E+02, 3.077E+02, 1.499E+00, 9.751E-04]  # Error: 1.4488E+05 * cell4
x0['6'] = [1.007E+01, 2.294E+03, 1.329E+02, 3.341E+02, 1.224E+00, 8.160E-04]  # Error: 1.2760E+05 * cell4

# x0['mean'] = [2.252E+02, 1.387E+03, 5.967E+01, 6.431E+02, 1.322E+00, 1.850E-03]  # Just these 6 cells 012317
x0['mean'] = [2.093E+02, 1.342E+03, 7.888E+01, 3.992E+02, 1.316E+00, 3.584E-03]  # Induced + Spontaneous

# to avoid saturation and reduce variability of time courses across cells, constrain the relative amplitude
# of global and local kernels:
# [local_rise_tau, local_decay_tau, global_rise_tau, global_decay_tau, filter_ratio, kernel_scale]

if cell_id in x0:
    x1 = x0[cell_id]
else:
    x1 = x0['mean']
xmin1 = [10., 500., 10., 100., 1., 5.e-4]
xmax1 = [500., 5000., 300., 2000., 1.5, 2.e-2]

for i in range(len(x1)):
    if x1[i] < xmin1[i]:
        x1[i] = xmin1[i]
    elif x1[i] > xmax1[i]:
        x1[i] = xmax1[i]

induction = 1

"""
result = optimize_explore(x1, xmin1, xmax1, ramp_error_cont, ramp[induction], induction, maxfev=700)

polished_result = optimize_polish(result['x'], xmin1, xmax1, ramp_error_cont, ramp[induction], induction)

polished_result = optimize_polish(x1, xmin1, xmax1, ramp_error_cont, ramp[induction], induction)

hist.report_best()
hist.export('011817_metaplasticity_optimization_cell'+cell_id)

ramp_error_cont(polished_result['x'], xmin1, xmax1, ramp[induction], induction, plot=True)
"""


for induction in position:
    if induction == 2 and 1 in position:
        this_model_baseline = model_baseline[1]
    else:
        this_model_baseline = None
    local_kernel[induction], global_kernel[induction], plasticity_signal[induction], model_ramp[induction], \
        model_baseline[induction] = ramp_error_cont(x1, xmin1, xmax1, ramp[induction], induction,
                                                    baseline=this_model_baseline, plot=False, full_output=True)
if 1 not in plasticity_signal:
    plasticity_signal[1] = np.zeros_like(peak_locs['CA3'])

w0 = {this_cell_id: {} for this_cell_id in x0.keys()+['7', '8', '9', '10', '11']}
if cell_id not in w0:
    w0[cell_id] = {}
binned_w1 = {}

# w0['1'][1] = [1.0530, 1.0519, 2.6067, 3.2128, 3.1777, 3.0347, 3.7553, 5.5801, 3.1213, 1.0425, 1.0600]
w0['1'][1] = [1.009E+00, 1.036E+00, 2.699E+00, 2.720E+00, 2.778E+00, 2.933E+00, 4.880E+00, 4.880E+00, 2.699E+00,
              1.130E+00, 1.134E+00]  # Error: 5.7215E+04
# w0['1'][2] = [4.106E+00, 4.177E+00, 5.043E+00, 2.002E+00, 1.654E+00, 1.577E+00, 4.445E+00, 1.807E+00, 1.495E+00,
#              2.310E+00, 3.116E+00]  # Error: 4.9474E+04
w0['1'][2] = [4.509E+00, 4.598E+00, 4.469E+00, 2.220E+00, 1.572E+00, 1.394E+00, 5.172E+00, 1.446E+00, 1.407E+00,
               2.672E+00, 2.978E+00]  # Error: 4.1328E+04
# w0['2'][1] = [2.663E+00, 2.661E+00, 1.280E+00, 1.280E+00, 3.258E+00, 3.254E+00, 1.210E+00, 1.141E+00, 1.141E+00,
#              1.146E+00, 2.064E+00]  # Error: 7.7499E+03
w0['2'][1] = [1.930E+00, 1.921E+00, 1.606E+00, 1.638E+00, 3.310E+00, 3.187E+00, 1.009E+00, 1.001E+00, 1.112E+00,
              1.418E+00, 2.871E+00]  # Error: 5.6634E+03
# w0['2'][2] = [3.153E+00, 1.047E+00, 2.259E+00, 2.742E+00, 2.366E+00, 1.691E+00, 1.520E+00, 1.296E+00, 1.636E+00,
#              2.839E+00, 2.519E+00]  # Error: 1.2036E+04
w0['2'][2] = [1.985E+00, 1.986E+00, 2.193E+00, 2.272E+00, 1.977E+00, 1.977E+00, 1.492E+00, 1.472E+00, 1.307E+00,
              2.993E+00, 2.941E+00]  # Error: 2.1846E+03
# w0['3'][1] = [1.003E+00, 1.000E+00, 1.724E+00, 4.276E+00, 2.942E+00, 2.088E+00, 3.293E+00, 3.499E+00, 2.662E+00,
#              1.483E+00, 1.508E+00]  # Error: 1.5349E+04
w0['3'][1] = [1.110E+00, 1.079E+00, 1.457E+00, 3.945E+00, 3.690E+00, 2.396E+00, 2.396E+00, 3.643E+00, 3.044E+00,
              1.412E+00, 1.181E+00]  # Error: 1.1389E+04
# w0['3'][2] = [1.012E+00, 1.011E+00, 1.004E+00, 2.621E+00, 3.760E+00, 3.929E+00, 2.144E+00, 2.224E+00, 3.136E+00,
#              3.069E+00, 2.564E+00]  # Error: 1.3052E+04
w0['3'][2] = [1.095E+00, 1.000E+00, 1.036E+00, 1.997E+00, 4.125E+00, 3.947E+00, 2.200E+00, 2.136E+00, 2.948E+00,
              2.897E+00, 2.896E+00]  # Error: 1.1020E+04
# w0['4'][1] = [2.367E+00, 1.198E+00, 1.000E+00, 1.086E+00, 2.255E+00, 3.899E+00, 3.900E+00, 3.128E+00, 2.133E+00,
#              1.955E+00, 4.017E+00]  # Error: 2.5967E+04
w0['4'][1] = [2.924E+00, 1.026E+00, 1.019E+00, 1.066E+00, 1.653E+00, 4.205E+00, 4.419E+00, 2.689E+00, 1.560E+00,
              2.123E+00, 4.143E+00]  # Error: 2.7947E+04
# w0['4'][2] = [1.502E+00, 1.569E+00, 1.569E+00, 1.842E+00, 4.461E+00, 4.461E+00, 3.114E+00, 1.729E+00, 1.758E+00,
#              3.292E+00, 3.292E+00]  # Error: 9.5853E+03
w0['4'][2] = [1.352E+00, 1.352E+00, 1.698E+00, 1.860E+00, 3.653E+00, 4.598E+00, 3.606E+00, 1.332E+00, 1.823E+00,
              3.440E+00, 3.440E+00]  # Error: 1.1517E+04
# w0['5'][1] = [1.295E+00, 1.295E+00, 3.116E+00, 3.102E+00, 3.150E+00, 2.966E+00, 2.620E+00, 1.283E+00, 1.283E+00,
#              1.271E+00, 1.507E+00]  # Error: 3.6282E+03
w0['5'][1] = [1.146E+00, 1.146E+00, 2.154E+00, 3.945E+00, 3.318E+00, 2.369E+00, 2.367E+00, 1.543E+00, 1.257E+00,
              1.257E+00, 1.257E+00]  # Error: 4.6300E+03
# w0['5'][2] = [2.798E+00, 3.066E+00, 3.311E+00, 3.311E+00, 1.740E+00, 2.015E+00, 2.418E+00, 2.418E+00, 1.518E+00,
#              1.238E+00, 1.434E+00]  # Error: 4.4590E+03
w0['5'][2] = [2.454E+00, 2.709E+00, 3.415E+00, 3.415E+00, 1.924E+00, 1.457E+00, 2.322E+00, 2.644E+00, 1.389E+00,
              1.159E+00, 1.432E+00]  # Error: 5.2998E+03
# w0['6'][1] = [3.264E+00, 1.720E+00, 1.023E+00, 2.285E+00, 3.685E+00, 1.785E+00, 1.000E+00, 2.977E+00, 4.806E+00,
#              1.824E+00, 3.255E+00]  # Error: 7.8322E+04
w0['6'][1] = [2.633E+00, 1.200E+00, 1.026E+00, 1.523E+00, 3.816E+00, 1.104E+00, 1.002E+00, 3.014E+00, 3.503E+00,
              1.859E+00, 3.597E+00]  # Error: 6.3231E+04
# w0['6'][2] = [1.519E+00, 1.833E+00, 1.907E+00, 2.115E+00, 5.258E+00, 3.127E+00, 1.829E+00, 1.831E+00, 3.596E+00,
#              4.382E+00, 4.379E+00]  # Error: 2.0410E+04
w0['6'][2] = [1.387E+00, 1.784E+00, 1.702E+00, 1.672E+00, 4.671E+00, 3.334E+00, 1.225E+00, 1.377E+00, 3.782E+00,
              3.786E+00, 3.785E+00]  # Error: 1.9045E+04
# w0['7'][1] = [2.717E+00, 2.993E+00, 2.519E+00, 1.206E+00, 1.087E+00, 1.339E+00, 1.705E+00, 1.751E+00, 2.945E+00,
#              2.939E+00, 3.440E+00]  # Error: 1.8074E+04
w0['7'][1] = [4.093E+00, 4.093E+00, 1.398E+00, 1.129E+00, 1.129E+00, 1.591E+00, 1.423E+00, 1.302E+00, 2.522E+00,
              2.718E+00, 2.787E+00]  # Error: 2.5141E+04
# w0['7'][2] = [1.646E+00, 1.194E+00, 1.187E+00, 3.289E+00, 3.233E+00, 3.234E+00, 3.190E+00, 3.688E+00, 4.119E+00,
#              3.452E+00, 3.503E+00]  # Error: 1.0075E+04
w0['7'][2] = [1.276E+00, 1.276E+00, 1.417E+00, 4.277E+00, 2.998E+00, 1.794E+00, 2.768E+00, 4.796E+00, 4.796E+00,
              2.271E+00, 2.206E+00]  # Error: 3.6525E+04
w0['8'][1] = [2.867E+00, 2.059E+00, 2.108E+00, 3.599E+00, 1.310E+00, 2.189E+00, 1.358E+00, 1.525E+00, 1.804E+00,
              1.010E+00, 2.506E+00]  # Error: 2.1018E+04
w0['8'][2] = [1.653E+00, 1.710E+00, 1.710E+00, 2.332E+00, 2.347E+00, 2.503E+00, 2.802E+00, 5.638E+00, 5.638E+00,
              1.489E+00, 1.489E+00]  # Error: 1.9957E+04
w0['10'][1] = [4.853E+00, 1.889E+00, 1.789E+00, 1.724E+00, 1.764E+00, 3.015E+00, 4.101E+00, 1.429E+00, 1.330E+00,
               1.291E+00, 2.338E+00]  # Error: 1.0682E+05
w0['10'][2] = [3.242E+00, 1.579E+00, 2.591E+00, 3.578E+00, 1.977E+00, 1.963E+00, 2.989E+00, 2.923E+00, 3.495E+00,
               2.864E+00, 2.227E+00]  # Error: 1.5536E+04
w0['11'][1] = [4.802E+00, 4.045E+00, 3.116E+00, 1.584E+00, 1.478E+00, 1.037E+00, 1.307E+00, 1.282E+00, 1.278E+00,
               1.593E+00, 4.614E+00]  # Error: 2.1412E+04
w0['11'][2] = [5.739E+00, 4.740E+00, 1.895E+00, 1.197E+00, 1.285E+00, 4.134E+00, 3.626E+00, 2.071E+00, 2.084E+00,
               1.618E+00, 1.236E+00]  # Error: 4.6156E+04


wmin1 = [1. for element in range(11)]
wmax1 = [7. for element in range(11)]

w1 = w0[cell_id]

binned_weights_dx = track_length / 10.
binned_weights_x = np.arange(0., track_length + binned_weights_dx / 2., binned_weights_dx)


for induction in ramp:
    if induction in w1:
        binned_w1[induction] = w1[induction]
    else:
        binned_w1[induction] = np.interp(binned_weights_x, peak_locs['CA3'], plasticity_signal[induction] + 1.)
    if induction == 2:
        this_model_baseline = model_baseline[1]
    else:
        this_model_baseline = None
    weights[induction], model_ramp[induction], model_baseline[induction], asymmetry[induction] = \
        ramp_error_ignore_kernel(binned_w1[induction], wmin1, wmax1, ramp[induction], induction,
                                 baseline=this_model_baseline, plot=False, full_output=True)

    """
    if induction in [1, 2]:  # [2]:
        result = optimize_explore(binned_w1[induction], wmin1, wmax1, ramp_error_ignore_kernel, ramp[induction],
                                 induction, baseline=this_model_baseline, maxfev=700)
        polished_result = optimize_polish(result['x'], wmin1, wmax1, ramp_error_ignore_kernel, ramp[induction],
                                          induction, baseline=this_model_baseline, maxfev=600)
        binned_w1[induction] = polished_result['x']

        # result = optimize_polish(binned_w1[induction], wmin1, wmax1, ramp_error_ignore_kernel, ramp[induction],
        #                          induction, baseline=this_model_baseline, maxfev=400)
        # binned_w1[induction] = result['x']

        weights[induction], model_ramp[induction], model_baseline[induction], asymmetry[induction] = \
            ramp_error_ignore_kernel(binned_w1[induction], wmin1, wmax1, ramp[induction], induction,
                                     baseline=this_model_baseline, plot=False, full_output=True)
    """


fig1, axes1 = plt.subplots(1)
fig2, axes2 = plt.subplots(1)

colors = ['black', 'r', 'c', 'grey']

mean_induction_loc, mean_induction_dur = {}, {}

for induction in ramp:
    mean_induction_loc[induction] = np.mean([induction_loc for induction_loc in induction_locs[induction] if 
                                             induction_loc is not None])
    mean_induction_dur[induction] = np.mean([induction_dur for induction_dur in induction_durs[induction] if
                                             induction_dur is not None])

for induction in ramp:
    axes1.plot(binned_x, ramp[induction], label='Experiment: Induction '+str(induction))
    axes1.plot(binned_x, model_ramp[induction], label='Model fit: Induction '+str(induction))
    axes1.set_xlabel('Location (cm)')
    axes1.set_ylabel('Ramp depolarization (mV)')
    axes1.set_xlim([0., track_length])
    axes1.legend(loc='best', frameon=False, framealpha=0.5)
    axes1.set_title('Induced Vm ramp depolarization')
    clean_axes(axes1)
    axes2.plot(peak_locs['CA3'], weights[induction], label='Induction '+str(induction))
    axes2.set_xlabel('Location (cm)')
    axes2.set_ylabel('Synaptic weight')
    axes2.set_title('Synaptic weight distributions')
    axes2.legend(loc='best', frameon=False, framealpha=0.5)
    clean_axes(axes2)

from matplotlib import cm
this_cm = cm.get_cmap()
colors = [this_cm(1.*i/2) for i in range(3)]
label_handles = []
label_handles.append(mlines.Line2D([], [], color=colors[0], label='Out of field'))
label_handles.append(mlines.Line2D([], [], color=colors[1], label='Before induction loc'))
label_handles.append(mlines.Line2D([], [], color=colors[2], label='After induction loc'))

delta_weights = {1: weights[1] - 1.}
if 2 in weights:
    delta_weights[2] = np.subtract(weights[2], weights[1])

for induction in ramp:
    if induction == 1:
        fig, axes3 = plt.subplots(1)
        axes3.scatter(plasticity_signal[induction], delta_weights[induction], c=asymmetry[induction], linewidth=0)
        axes3.set_xlabel('Plasticity signal (a.u.)')
        axes3.set_ylabel('Change in synaptic weight')
        axes3.set_title('Metaplasticity - Induction '+str(induction))
        axes3.legend(handles=label_handles, framealpha=0.5, frameon=False)
        clean_axes(axes3)
    elif induction == 2:
        fig = plt.figure()
        axes4 = fig.add_subplot(111, projection='3d')
        axes4.scatter(plasticity_signal[induction], weights[1], delta_weights[induction], c=asymmetry[induction],
                      linewidth=0)
        axes4.set_xlabel('Plasticity signal (a.u.)')
        axes4.set_ylabel('Initial synaptic weight')
        axes4.set_zlabel('Change in synaptic weight')
        axes4.set_title('Metaplasticity - Induction ' + str(induction))
        axes4.legend(handles=label_handles, framealpha=0.5, frameon=False)
plt.show()
plt.close()

"""
with h5py.File(experimental_file_dir+experimental_filename+'.hdf5', 'a') as f:
    for induction in ramp:
        if cell_id not in f:
            raise Exception('Cell id %s not in output file.' % cell_id)
        f[cell_id][str(induction)].attrs['mean_induction_loc'] = mean_induction_loc[induction]
        f[cell_id][str(induction)].attrs['mean_induction_dur'] = mean_induction_dur[induction]
        f[cell_id][str(induction)].create_dataset('smooth_ramp', compression='gzip', compression_opts=9,
                                                  data=ramp[induction])
        f[cell_id][str(induction)].create_dataset('model_ramp', compression='gzip', compression_opts=9,
                                                  data=model_ramp[induction])
        f[cell_id][str(induction)].create_dataset('weights', compression='gzip', compression_opts=9,
                                                  data=weights[induction])
        f[cell_id][str(induction)].create_dataset('delta_weights', compression='gzip', compression_opts=9,
                                                  data=delta_weights[induction])
        f[cell_id][str(induction)].create_dataset('plasticity_signal', compression='gzip', compression_opts=9,
                                                  data=plasticity_signal[induction])
"""