#Targets for SOMA plateau with Theta burst stimulation
targets:
  plateau_area: 17.193741965716423
  avg_spikes_per_cycle: 4.083333333333333

parameters:
  # Conductance Multipliers (Broadened Search)

#20260321
#   final_error: 0.1192
# parameters:
#   channels:
#     cal: 0.4714
#     calH: 1.0241
#     car: 1.0653
#     cat: 1.0844
#     kca: 1.0622
#     mykca: 1.1891
#   synapses:
#     exc_CA3: 100
#     exc_ECIII: 102
#     inh_CA3: 102
#     inh_ECIII: 109

  parameters:
  # Conductance Multipliers (Now the only things being optimized)
  cal:
    initial_value: 0.4714
    bounds: [0.1, 1.5]
  calH:
    initial_value: 1.0241
    bounds: [0.5, 1.1] # TIGHTER: Prevents Depo Block
  car:
    initial_value: 1.0653
    bounds: [0.5, 1.5]
  cat:
    initial_value: 1.0844
    bounds: [0.5, 1.5]
  mykca:
    initial_value: 1.1891
    bounds: [0.1, 2.0]
  kca:
    initial_value: 1.0622
    bounds: [0.5, 2.0] # HIGHER FLOOR: Forces repolarization
    
  # Synapse Counts (SET AS CONSTANTS to stop the 'noise')

# num_exc_syns = {'ECIII': 135, 'CA3': 73}
# num_inh_syns = {'ECIII': 118, 'CA3': 79} 

  exc_CA3: 73
  exc_ECIII: 135
  inh_CA3: 79
  inh_ECIII: 118

simulation:
  morph_filename: EB2-late-bifurcation.swc
  mech_filename: 20260319_default_biophysics_with_Calcium_Channels.yaml
  equilibrate: 250.0
  sim_duration: 2500.0
  dt: 0.025
  v_init: -70.0
  tbs_times: [500., 510., 520., 530., 540., 650., 660., 670., 680., 690., 800., 810., 820., 830., 840., 950., 960., 970., 980., 990., 1100., 1110., 1120., 1130., 1140.]

Optimizer: L-BFGS-B
num_iterations: 5
num_evaluations: #
